-- Generate a solution-level androidfile.
--
-- originally from:
-- Copyright (c) 2012 Richard Swift and the Premake project

local jni = premake.extensions.jni

function jni.solution(sln)
	-- write a header showing the build options
	_p('# %s solution makefile autogenerated by Premake', premake.action.current().shortname)
	_p('APP_PROJECT_PATH := %s', sln.basedir)
	_p('APP_BUILD_SCRIPT := Android.mk')
	_p('APP_ABI := all')
	_p('')
end
