-- Generate a solution-level manifest.
--
-- originally from:
-- Copyright (c) 2012 Richard Swift and the Premake project

local jni = premake.extensions.jni

function jni.manifest(sln)
	-- write a header showing the build options
	_p('<!-- Empty manifest autogenerated by Premake -->')
	_p('')			
end
