function (minko_enable_plugin_jpeg target)
    set (JPEG_PATH "${MINKO_HOME}/plugin/jpeg")
    minko_plugin_link ("jpeg" ${target})
    target_include_directories(${target} PRIVATE "${JPEG_PATH}/include")
    target_compile_options(${target} PRIVATE "-DMINKO_PLUGIN_JPEG")
endfunction ()