stages:
  - build

html5_release:
  stage: build
  image: trzeci/emscripten:sdk-tag-1.37.3-64bit
  script:
    - apt-get update && apt-get install -y make # https://github.com/asRIA/emscripten-docker/issues/1
    - cd script
    - ./solution_gmake_min.sh --no-glsl-optimizer
    - ./build_html5_release.sh -j$(nproc)

android_release:
  stage: build
  image: alexisduque/android-ndk-gradle-docker:latest
  script:
    # https://github.com/aerys/minko/blob/master/doc/tutorial/Compiling_the_SDK_for_Android.md
    - mkdir -p /opt/android-sdk-linux/ndk
    - ln -s /opt/android-ndk-r13b /opt/android-sdk-linux/ndk/android-ndk-r13b
    - ln -s /opt/android-sdk-linux/build-tools/25.0.2/zipalign /opt/android-sdk-linux/zipalign
    - cd script
    - ./install_jni.sh
    - ./solution_gmake_min.sh
    - ./build_android_release.sh -j$(nproc)

linux_release:
    stage: build
    image: gcc:6.2
    script:
      - apt-get update && apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libglew-dev libsdl2-dev libgtk2.0-dev libgtkglext1
      - cd script
      - ./solution_gmake_min.sh
      - cd ..
      - make -j$(nproc) config=linux64_release
