stages:
  - build

html5_release:
    stage: build
    image: trzeci/emscripten:sdk-tag-1.37.3-64bit
    script:
    - apt-get update && apt-get install -y make # https://github.com/asRIA/emscripten-docker/issues/1
    - cd script
    - ./solution_gmake_min.sh
    - ./build_html5_release.sh

android_release:
    state: build
    image: bitriseio/android-ndk:v2017_01_28-10_06-b344
    - cd script
    - ./solution_gmake_min.sh
    - ./build_android_release.sh
