include:
  - project: 'aerys/infrastructure/gitlab-ci-templates'
    ref: 'v0.7.2'
    file: '/jobs/docker-in-docker/Docker-In-Docker.gitlab-ci.yml'
  - project: 'aerys/infrastructure/gitlab-ci-templates'
    ref: 'v0.7.2'
    file: '/jobs/commitlint/commintlint.gitlab-ci.yml'
  - project: 'aerys/infrastructure/gitlab-ci-templates'
    ref: 'v0.7.2'
    file: '/jobs/semantic-release/semantic-release.gitlab-ci.yml'

variables:
  DOCKER_BUILD_FORCE:
    value: "false"
    description: "Force a build of the container images."
  DOCKER_PUSH_FORCE:
    value: "false"
    description: "Force the container images to be pushed to the registry even if an image with the same label exists."

stages:
  - build
  - test
  - check
  - publish
  - release

.docker_build_template: &docker_build_template
  stage: build
  tags:
    - virtualbox
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - docker/$DOCKER_IMAGE_NAME/Dockerfile
    - if: $DOCKER_BUILD_FORCE == "true"
  artifacts:
    expire_in: 1 hr
    paths:
      - ./docker-image.tar
  before_script:
    - docker info
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_NAME}:${CI_PIPELINE_ID} docker/${DOCKER_IMAGE_NAME}
    - docker save ${CI_REGISTRY_IMAGE}/${DOCKER_IMAGE_NAME}:${CI_PIPELINE_ID} -o docker-image.tar

.build_with_artifacts_template: &build_with_artifacts_template
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    expire_in: 6 hr
    paths:
      - build/module
      - build/framework/enable.cmake
      - build/framework/bin
      - build/framework/asset
      - build/framework/lib
      - build/framework/include
      - build/plugin/*/bin
      - build/plugin/*/asset
      - build/plugin/*/lib
      - build/plugin/*/include
      - build/plugin/*/enable.cmake
      - build/plugin/html-overlay/src/android/tasks/*.java
      - build/plugin/html-overlay/src/android/webview/*.java
      - build/plugin/sensors/src/android/*.java
      - build/plugin/nodejs-worker/src/minko/file/*.java
      - build/plugin/video-camera/src/minko/video/*.java
      - build/template
      - build/cmake
      - build/test
      - LICENSE.md
      - README.md

.build_template: &build_template
  stage: build
  extends:
    - .docker-in-docker
    - .build_with_artifacts_template
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - apk add bash
  script:
    - BUILD_DIR=build bash script/build.sh $TARGET_PLATFORM release

.publish_template: &publish_template
  image: registry.aerys.in/aerys/infrastructure/vendor/rust-docker:1.72.0-1
  stage: publish
  only:
    - main
    - tags
  script:
    - PACKAGE_VERSION="main" # Default
    - PACKAGE_VERSION=$(([[ "$CI_COMMIT_TAG" ]] && echo "$CI_COMMIT_TAG") || echo "$PACKAGE_VERSION")
    - ARCHIVE_NAME="${CI_PROJECT_NAME}-${PLATFORM}-${PACKAGE_VERSION}.tar.bz2"
    - apt-get update && apt-get install -y jq
    - cd "${CI_PROJECT_DIR}"
    - tar -cjSf "/tmp/${ARCHIVE_NAME}" *
    # Publish the package.
    - 'curl --fail --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "/tmp/${ARCHIVE_NAME}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${PACKAGE_VERSION}/${ARCHIVE_NAME}"'

build:html5:
  <<: *build_template
  variables:
    TARGET_PLATFORM: html5

build:android32:
  <<: *build_template
  variables:
    TARGET_PLATFORM: android32

build:android64:
  <<: *build_template
  variables:
    TARGET_PLATFORM: android64

build:linux64_offscreen:
  <<: *build_template
  variables:
    TARGET_PLATFORM: linux64_offscreen

build:windows64:
  <<: *build_with_artifacts_template
  stage: build
  tags:
    - windows
  script:
    - $env:MINKO_HOME="{0}" -f (Get-Location).ToString()
    - New-Item -ItemType Directory -Force -Path build
    - Set-Location -Path build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DWITH_EXAMPLES=OFF -DWITH_PLUGINS=ON ..
    - msbuild Project.sln /property:Configuration=Release /property:Platform=x64 /m:4

build:windows64_offscreen:
  <<: *build_with_artifacts_template
  stage: build
  tags:
    - windows
  script:
    - $env:MINKO_HOME="{0}" -f (Get-Location).ToString()
    - New-Item -ItemType Directory -Force -Path build
    - Set-Location -Path build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DWITH_EXAMPLES=OFF -DWITH_PLUGINS=ON -DWITH_OFFSCREEN=ON -DWITH_TEXTURE_COMPRESSOR=ON -DWITH_TESTS=ON ..
    - msbuild Project.sln /property:Configuration=Release /property:Platform=x64 /m:4

# Disabled until https://git.aerys.in/aerys/smartshape-engine/issues/166 is fixed.
# test:windows64_offscreen:
#   stage: test
#   tags:
#     - windows
#   dependencies:
#     - build:windows64_offscreen
#   artifacts:
#     name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
#     when: on_failure
#     expire_in: 1 hr
#     paths:
#       - build/test
#   script:
#     - cd .\build\test\bin
#     - minko-test.exe

test:linux64_offscreen:
  stage: test
  image: registry.aerys.in/aerys/smartshape/vendor/gcc@sha256:d4a63069d9b69ca4233eecd17638356d7e01aeb66f447db5b3e606a75f527887
  dependencies:
    - build:linux64_offscreen
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    when: on_failure
    expire_in: 1 hr
    paths:
      - build/test
  before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - cd ./test/websocket-server
    - pip3 install -r requirements.txt
    - python3 server.py &
    - WS_SERVER_PID=$!
    - python3 tls_server.py &
    - WSS_SERVER_PID=$!
  script:
    - cd "${CI_PROJECT_DIR}/build/test/bin"
    - ./minko-test
    - kill -SIGINT ${WS_SERVER_PID}
    - kill -SIGINT ${WSS_SERVER_PID}
    - wait

build:linux64:
  <<: *build_template
  variables:
    TARGET_PLATFORM: linux64

lint:commitlint:
  extends: .commitlint
  stage: check

check:semantic-release:
  stage: check
  extends: .semantic-release-dry-run

publish:linux64:
  <<: *publish_template
  dependencies:
    - build:linux64
  variables:
    PLATFORM: "linux-amd64-gcc-9.4"

publish:linux64_offscreen:
  <<: *publish_template
  dependencies:
    - build:linux64_offscreen
  variables:
    PLATFORM: "linux-amd64-gcc-9.4-offscreen"

publish:android32:
  <<: *publish_template
  dependencies:
    - build:android32
  variables:
    PLATFORM: "android-armeabi-v7a-r25b"

publish:android64:
  <<: *publish_template
  dependencies:
    - build:android64
  variables:
    PLATFORM: "android-arm64-v8a-r25b"

publish:html5:
  <<: *publish_template
  dependencies:
    - build:html5
  variables:
    PLATFORM: "emscripten-wasm"

publish:windows64:
  <<: *publish_template
  dependencies:
    - build:windows64
  variables:
    PLATFORM: "windows-amd64-msvc"

publish:windows64_offscreen:
  <<: *publish_template
  dependencies:
    - build:windows64_offscreen
  variables:
    PLATFORM: "windows-amd64-msvc-offscreen"

release:
  stage: release
  extends: .semantic-release
