function (plugin_link plugin_name target)
# add specifications see : module/minko/minko.plugin.lua
    #foreach(name IN_LISTS names)
        target_link_libraries(${target} minko-plugin-${plugin_name})
    #endforeach()
endfunction ()

function(call_plugin _id plugin project_name)
    if (NOT COMMAND ${_id})
        message(FATAL_ERROR "The \"${plugin}\" is not build for project \"${project_name}\".")
    else()
        set(_helper "${CMAKE_BINARY_DIR}/helpers/macro_helper_${_id}.cmake")
        if (NOT EXISTS "${_helper}")
            file(WRITE "${_helper}" "${_id}(\$\{PROJECT_NAME\})\n")
        endif()
        include("${_helper}")
    endif()
endfunction()