function(minko_enable_plugin_png target)
    minko_plugin_link("png" ${target})
    set(PNG_PATH "${MINKO_HOME}/plugin/png")
    target_include_directories(${target} PRIVATE "${PNG_PATH}/include")
    add_definitions("-DMINKO_PLUGIN_PNG")
endfunction()
