function (enable_ttf target)
    plugin_link("ttf" ${target})
    target_compile_options(${target} PUBLIC "-DMINKO_PLUGIN_TTF")
    set(TTF_PATH "${MINKO_HOME}/plugin/ttf")
    target_include_directories(${target} PUBLIC "${TTF_PATH}/include")
    
    if (WIN32)
        target_compile_options(${target} PUBLIC "-DMINKO_PLUGIN_TTF_FREETYPE")
        target_link_libraries(${target} "${TTF_PATH}/lib/freetype/lib/windows${BITNESS}/freetype28.lib")
        configure_file("${TTF_PATH}/lib/freetype/lib/windows${BITNESS}/freetype28.dll" "${OUTPUT_PATH}" COPYONLY) 
        set_target_properties(${target} PROPERTIES LINK_FLAGS "/NODEFAULTLIB:msvcrt.lib")       
    endif ()
    
    if (UNIX AND NOT APPLE AND NOT EMSCRIPTEN AND NOT ANDROID)
        target_compile_options(${target} PUBLIC "-DMINKO_PLUGIN_TTF_FREETYPE")
        target_link_libraries(${target} "freetype")
    endif ()
endfunction ()