function (minko_enable_plugin_ttf target)
    minko_plugin_link("ttf" ${target})
    target_compile_options(${target} PRIVATE "-DMINKO_PLUGIN_TTF")
    set(TTF_PATH "${MINKO_HOME}/plugin/ttf")
    target_include_directories(${target} PRIVATE "${TTF_PATH}/include")
    
    if (WIN32)
        target_compile_options(${target} PRIVATE "-DMINKO_PLUGIN_TTF_FREETYPE")
        target_link_libraries(${target} "${TTF_PATH}/lib/freetype/lib/windows${BITNESS}/freetype28.lib")
        if (DLL STREQUAL "ON")
            string(FIND ${target} "minko-plugin" TEST_PLUGIN)
            if (TEST_PLUGIN STREQUAL -1)
                configure_file("${TTF_PATH}/lib/freetype/lib/windows${BITNESS}/freetype28.dll" "${OUTPUT_PATH}" COPYONLY)
            endif ()
        else ()
            configure_file("${TTF_PATH}/lib/freetype/lib/windows${BITNESS}/freetype28.dll" "${OUTPUT_PATH}" COPYONLY)
        endif ()
    endif ()
    
    if (LINUX)
        target_compile_options(${target} PRIVATE "-DMINKO_PLUGIN_TTF_FREETYPE")
        target_link_libraries(${target} "freetype")
    endif ()
endfunction ()