package aerys.minko.render.shader.node
{
	public final class Components
	{
		public static const X : uint = 0 | (4 << 4) | (4 << 8) | (4 << 12);
		public static const Y : uint = 1 | (4 << 4) | (4 << 8) | (4 << 12);
		public static const Z : uint = 2 | (4 << 4) | (4 << 8) | (4 << 12);
		public static const W : uint = 3 | (4 << 4) | (4 << 8) | (4 << 12);
		public static const XX : uint = 0 | (0 << 4) | (4 << 8) | (4 << 12);
		public static const XY : uint = 0 | (1 << 4) | (4 << 8) | (4 << 12);
		public static const XZ : uint = 0 | (2 << 4) | (4 << 8) | (4 << 12);
		public static const XW : uint = 0 | (3 << 4) | (4 << 8) | (4 << 12);
		public static const YX : uint = 1 | (0 << 4) | (4 << 8) | (4 << 12);
		public static const YY : uint = 1 | (1 << 4) | (4 << 8) | (4 << 12);
		public static const YZ : uint = 1 | (2 << 4) | (4 << 8) | (4 << 12);
		public static const YW : uint = 1 | (3 << 4) | (4 << 8) | (4 << 12);
		public static const ZX : uint = 2 | (0 << 4) | (4 << 8) | (4 << 12);
		public static const ZY : uint = 2 | (1 << 4) | (4 << 8) | (4 << 12);
		public static const ZZ : uint = 2 | (2 << 4) | (4 << 8) | (4 << 12);
		public static const ZW : uint = 2 | (3 << 4) | (4 << 8) | (4 << 12);
		public static const WX : uint = 3 | (0 << 4) | (4 << 8) | (4 << 12);
		public static const WY : uint = 3 | (1 << 4) | (4 << 8) | (4 << 12);
		public static const WZ : uint = 3 | (2 << 4) | (4 << 8) | (4 << 12);
		public static const WW : uint = 3 | (3 << 4) | (4 << 8) | (4 << 12);
		public static const XXX : uint = 0 | (0 << 4) | (0 << 8) | (4 << 12);
		public static const XXY : uint = 0 | (0 << 4) | (1 << 8) | (4 << 12);
		public static const XXZ : uint = 0 | (0 << 4) | (2 << 8) | (4 << 12);
		public static const XXW : uint = 0 | (0 << 4) | (3 << 8) | (4 << 12);
		public static const XYX : uint = 0 | (1 << 4) | (0 << 8) | (4 << 12);
		public static const XYY : uint = 0 | (1 << 4) | (1 << 8) | (4 << 12);
		public static const XYZ : uint = 0 | (1 << 4) | (2 << 8) | (4 << 12);
		public static const XYW : uint = 0 | (1 << 4) | (3 << 8) | (4 << 12);
		public static const XZX : uint = 0 | (2 << 4) | (0 << 8) | (4 << 12);
		public static const XZY : uint = 0 | (2 << 4) | (1 << 8) | (4 << 12);
		public static const XZZ : uint = 0 | (2 << 4) | (2 << 8) | (4 << 12);
		public static const XZW : uint = 0 | (2 << 4) | (3 << 8) | (4 << 12);
		public static const XWX : uint = 0 | (3 << 4) | (0 << 8) | (4 << 12);
		public static const XWY : uint = 0 | (3 << 4) | (1 << 8) | (4 << 12);
		public static const XWZ : uint = 0 | (3 << 4) | (2 << 8) | (4 << 12);
		public static const XWW : uint = 0 | (3 << 4) | (3 << 8) | (4 << 12);
		public static const YXX : uint = 1 | (0 << 4) | (0 << 8) | (4 << 12);
		public static const YXY : uint = 1 | (0 << 4) | (1 << 8) | (4 << 12);
		public static const YXZ : uint = 1 | (0 << 4) | (2 << 8) | (4 << 12);
		public static const YXW : uint = 1 | (0 << 4) | (3 << 8) | (4 << 12);
		public static const YYX : uint = 1 | (1 << 4) | (0 << 8) | (4 << 12);
		public static const YYY : uint = 1 | (1 << 4) | (1 << 8) | (4 << 12);
		public static const YYZ : uint = 1 | (1 << 4) | (2 << 8) | (4 << 12);
		public static const YYW : uint = 1 | (1 << 4) | (3 << 8) | (4 << 12);
		public static const YZX : uint = 1 | (2 << 4) | (0 << 8) | (4 << 12);
		public static const YZY : uint = 1 | (2 << 4) | (1 << 8) | (4 << 12);
		public static const YZZ : uint = 1 | (2 << 4) | (2 << 8) | (4 << 12);
		public static const YZW : uint = 1 | (2 << 4) | (3 << 8) | (4 << 12);
		public static const YWX : uint = 1 | (3 << 4) | (0 << 8) | (4 << 12);
		public static const YWY : uint = 1 | (3 << 4) | (1 << 8) | (4 << 12);
		public static const YWZ : uint = 1 | (3 << 4) | (2 << 8) | (4 << 12);
		public static const YWW : uint = 1 | (3 << 4) | (3 << 8) | (4 << 12);
		public static const ZXX : uint = 2 | (0 << 4) | (0 << 8) | (4 << 12);
		public static const ZXY : uint = 2 | (0 << 4) | (1 << 8) | (4 << 12);
		public static const ZXZ : uint = 2 | (0 << 4) | (2 << 8) | (4 << 12);
		public static const ZXW : uint = 2 | (0 << 4) | (3 << 8) | (4 << 12);
		public static const ZYX : uint = 2 | (1 << 4) | (0 << 8) | (4 << 12);
		public static const ZYY : uint = 2 | (1 << 4) | (1 << 8) | (4 << 12);
		public static const ZYZ : uint = 2 | (1 << 4) | (2 << 8) | (4 << 12);
		public static const ZYW : uint = 2 | (1 << 4) | (3 << 8) | (4 << 12);
		public static const ZZX : uint = 2 | (2 << 4) | (0 << 8) | (4 << 12);
		public static const ZZY : uint = 2 | (2 << 4) | (1 << 8) | (4 << 12);
		public static const ZZZ : uint = 2 | (2 << 4) | (2 << 8) | (4 << 12);
		public static const ZZW : uint = 2 | (2 << 4) | (3 << 8) | (4 << 12);
		public static const ZWX : uint = 2 | (3 << 4) | (0 << 8) | (4 << 12);
		public static const ZWY : uint = 2 | (3 << 4) | (1 << 8) | (4 << 12);
		public static const ZWZ : uint = 2 | (3 << 4) | (2 << 8) | (4 << 12);
		public static const ZWW : uint = 2 | (3 << 4) | (3 << 8) | (4 << 12);
		public static const WXX : uint = 3 | (0 << 4) | (0 << 8) | (4 << 12);
		public static const WXY : uint = 3 | (0 << 4) | (1 << 8) | (4 << 12);
		public static const WXZ : uint = 3 | (0 << 4) | (2 << 8) | (4 << 12);
		public static const WXW : uint = 3 | (0 << 4) | (3 << 8) | (4 << 12);
		public static const WYX : uint = 3 | (1 << 4) | (0 << 8) | (4 << 12);
		public static const WYY : uint = 3 | (1 << 4) | (1 << 8) | (4 << 12);
		public static const WYZ : uint = 3 | (1 << 4) | (2 << 8) | (4 << 12);
		public static const WYW : uint = 3 | (1 << 4) | (3 << 8) | (4 << 12);
		public static const WZX : uint = 3 | (2 << 4) | (0 << 8) | (4 << 12);
		public static const WZY : uint = 3 | (2 << 4) | (1 << 8) | (4 << 12);
		public static const WZZ : uint = 3 | (2 << 4) | (2 << 8) | (4 << 12);
		public static const WZW : uint = 3 | (2 << 4) | (3 << 8) | (4 << 12);
		public static const WWX : uint = 3 | (3 << 4) | (0 << 8) | (4 << 12);
		public static const WWY : uint = 3 | (3 << 4) | (1 << 8) | (4 << 12);
		public static const WWZ : uint = 3 | (3 << 4) | (2 << 8) | (4 << 12);
		public static const WWW : uint = 3 | (3 << 4) | (3 << 8) | (4 << 12);
		public static const XXXX : uint = 0 | (0 << 4) | (0 << 8) | (0 << 12);
		public static const XXXY : uint = 0 | (0 << 4) | (0 << 8) | (1 << 12);
		public static const XXXZ : uint = 0 | (0 << 4) | (0 << 8) | (2 << 12);
		public static const XXXW : uint = 0 | (0 << 4) | (0 << 8) | (3 << 12);
		public static const XXYX : uint = 0 | (0 << 4) | (1 << 8) | (0 << 12);
		public static const XXYY : uint = 0 | (0 << 4) | (1 << 8) | (1 << 12);
		public static const XXYZ : uint = 0 | (0 << 4) | (1 << 8) | (2 << 12);
		public static const XXYW : uint = 0 | (0 << 4) | (1 << 8) | (3 << 12);
		public static const XXZX : uint = 0 | (0 << 4) | (2 << 8) | (0 << 12);
		public static const XXZY : uint = 0 | (0 << 4) | (2 << 8) | (1 << 12);
		public static const XXZZ : uint = 0 | (0 << 4) | (2 << 8) | (2 << 12);
		public static const XXZW : uint = 0 | (0 << 4) | (2 << 8) | (3 << 12);
		public static const XXWX : uint = 0 | (0 << 4) | (3 << 8) | (0 << 12);
		public static const XXWY : uint = 0 | (0 << 4) | (3 << 8) | (1 << 12);
		public static const XXWZ : uint = 0 | (0 << 4) | (3 << 8) | (2 << 12);
		public static const XXWW : uint = 0 | (0 << 4) | (3 << 8) | (3 << 12);
		public static const XYXX : uint = 0 | (1 << 4) | (0 << 8) | (0 << 12);
		public static const XYXY : uint = 0 | (1 << 4) | (0 << 8) | (1 << 12);
		public static const XYXZ : uint = 0 | (1 << 4) | (0 << 8) | (2 << 12);
		public static const XYXW : uint = 0 | (1 << 4) | (0 << 8) | (3 << 12);
		public static const XYYX : uint = 0 | (1 << 4) | (1 << 8) | (0 << 12);
		public static const XYYY : uint = 0 | (1 << 4) | (1 << 8) | (1 << 12);
		public static const XYYZ : uint = 0 | (1 << 4) | (1 << 8) | (2 << 12);
		public static const XYYW : uint = 0 | (1 << 4) | (1 << 8) | (3 << 12);
		public static const XYZX : uint = 0 | (1 << 4) | (2 << 8) | (0 << 12);
		public static const XYZY : uint = 0 | (1 << 4) | (2 << 8) | (1 << 12);
		public static const XYZZ : uint = 0 | (1 << 4) | (2 << 8) | (2 << 12);
		public static const XYZW : uint = 0 | (1 << 4) | (2 << 8) | (3 << 12);
		public static const XYWX : uint = 0 | (1 << 4) | (3 << 8) | (0 << 12);
		public static const XYWY : uint = 0 | (1 << 4) | (3 << 8) | (1 << 12);
		public static const XYWZ : uint = 0 | (1 << 4) | (3 << 8) | (2 << 12);
		public static const XYWW : uint = 0 | (1 << 4) | (3 << 8) | (3 << 12);
		public static const XZXX : uint = 0 | (2 << 4) | (0 << 8) | (0 << 12);
		public static const XZXY : uint = 0 | (2 << 4) | (0 << 8) | (1 << 12);
		public static const XZXZ : uint = 0 | (2 << 4) | (0 << 8) | (2 << 12);
		public static const XZXW : uint = 0 | (2 << 4) | (0 << 8) | (3 << 12);
		public static const XZYX : uint = 0 | (2 << 4) | (1 << 8) | (0 << 12);
		public static const XZYY : uint = 0 | (2 << 4) | (1 << 8) | (1 << 12);
		public static const XZYZ : uint = 0 | (2 << 4) | (1 << 8) | (2 << 12);
		public static const XZYW : uint = 0 | (2 << 4) | (1 << 8) | (3 << 12);
		public static const XZZX : uint = 0 | (2 << 4) | (2 << 8) | (0 << 12);
		public static const XZZY : uint = 0 | (2 << 4) | (2 << 8) | (1 << 12);
		public static const XZZZ : uint = 0 | (2 << 4) | (2 << 8) | (2 << 12);
		public static const XZZW : uint = 0 | (2 << 4) | (2 << 8) | (3 << 12);
		public static const XZWX : uint = 0 | (2 << 4) | (3 << 8) | (0 << 12);
		public static const XZWY : uint = 0 | (2 << 4) | (3 << 8) | (1 << 12);
		public static const XZWZ : uint = 0 | (2 << 4) | (3 << 8) | (2 << 12);
		public static const XZWW : uint = 0 | (2 << 4) | (3 << 8) | (3 << 12);
		public static const XWXX : uint = 0 | (3 << 4) | (0 << 8) | (0 << 12);
		public static const XWXY : uint = 0 | (3 << 4) | (0 << 8) | (1 << 12);
		public static const XWXZ : uint = 0 | (3 << 4) | (0 << 8) | (2 << 12);
		public static const XWXW : uint = 0 | (3 << 4) | (0 << 8) | (3 << 12);
		public static const XWYX : uint = 0 | (3 << 4) | (1 << 8) | (0 << 12);
		public static const XWYY : uint = 0 | (3 << 4) | (1 << 8) | (1 << 12);
		public static const XWYZ : uint = 0 | (3 << 4) | (1 << 8) | (2 << 12);
		public static const XWYW : uint = 0 | (3 << 4) | (1 << 8) | (3 << 12);
		public static const XWZX : uint = 0 | (3 << 4) | (2 << 8) | (0 << 12);
		public static const XWZY : uint = 0 | (3 << 4) | (2 << 8) | (1 << 12);
		public static const XWZZ : uint = 0 | (3 << 4) | (2 << 8) | (2 << 12);
		public static const XWZW : uint = 0 | (3 << 4) | (2 << 8) | (3 << 12);
		public static const XWWX : uint = 0 | (3 << 4) | (3 << 8) | (0 << 12);
		public static const XWWY : uint = 0 | (3 << 4) | (3 << 8) | (1 << 12);
		public static const XWWZ : uint = 0 | (3 << 4) | (3 << 8) | (2 << 12);
		public static const XWWW : uint = 0 | (3 << 4) | (3 << 8) | (3 << 12);
		public static const YXXX : uint = 1 | (0 << 4) | (0 << 8) | (0 << 12);
		public static const YXXY : uint = 1 | (0 << 4) | (0 << 8) | (1 << 12);
		public static const YXXZ : uint = 1 | (0 << 4) | (0 << 8) | (2 << 12);
		public static const YXXW : uint = 1 | (0 << 4) | (0 << 8) | (3 << 12);
		public static const YXYX : uint = 1 | (0 << 4) | (1 << 8) | (0 << 12);
		public static const YXYY : uint = 1 | (0 << 4) | (1 << 8) | (1 << 12);
		public static const YXYZ : uint = 1 | (0 << 4) | (1 << 8) | (2 << 12);
		public static const YXYW : uint = 1 | (0 << 4) | (1 << 8) | (3 << 12);
		public static const YXZX : uint = 1 | (0 << 4) | (2 << 8) | (0 << 12);
		public static const YXZY : uint = 1 | (0 << 4) | (2 << 8) | (1 << 12);
		public static const YXZZ : uint = 1 | (0 << 4) | (2 << 8) | (2 << 12);
		public static const YXZW : uint = 1 | (0 << 4) | (2 << 8) | (3 << 12);
		public static const YXWX : uint = 1 | (0 << 4) | (3 << 8) | (0 << 12);
		public static const YXWY : uint = 1 | (0 << 4) | (3 << 8) | (1 << 12);
		public static const YXWZ : uint = 1 | (0 << 4) | (3 << 8) | (2 << 12);
		public static const YXWW : uint = 1 | (0 << 4) | (3 << 8) | (3 << 12);
		public static const YYXX : uint = 1 | (1 << 4) | (0 << 8) | (0 << 12);
		public static const YYXY : uint = 1 | (1 << 4) | (0 << 8) | (1 << 12);
		public static const YYXZ : uint = 1 | (1 << 4) | (0 << 8) | (2 << 12);
		public static const YYXW : uint = 1 | (1 << 4) | (0 << 8) | (3 << 12);
		public static const YYYX : uint = 1 | (1 << 4) | (1 << 8) | (0 << 12);
		public static const YYYY : uint = 1 | (1 << 4) | (1 << 8) | (1 << 12);
		public static const YYYZ : uint = 1 | (1 << 4) | (1 << 8) | (2 << 12);
		public static const YYYW : uint = 1 | (1 << 4) | (1 << 8) | (3 << 12);
		public static const YYZX : uint = 1 | (1 << 4) | (2 << 8) | (0 << 12);
		public static const YYZY : uint = 1 | (1 << 4) | (2 << 8) | (1 << 12);
		public static const YYZZ : uint = 1 | (1 << 4) | (2 << 8) | (2 << 12);
		public static const YYZW : uint = 1 | (1 << 4) | (2 << 8) | (3 << 12);
		public static const YYWX : uint = 1 | (1 << 4) | (3 << 8) | (0 << 12);
		public static const YYWY : uint = 1 | (1 << 4) | (3 << 8) | (1 << 12);
		public static const YYWZ : uint = 1 | (1 << 4) | (3 << 8) | (2 << 12);
		public static const YYWW : uint = 1 | (1 << 4) | (3 << 8) | (3 << 12);
		public static const YZXX : uint = 1 | (2 << 4) | (0 << 8) | (0 << 12);
		public static const YZXY : uint = 1 | (2 << 4) | (0 << 8) | (1 << 12);
		public static const YZXZ : uint = 1 | (2 << 4) | (0 << 8) | (2 << 12);
		public static const YZXW : uint = 1 | (2 << 4) | (0 << 8) | (3 << 12);
		public static const YZYX : uint = 1 | (2 << 4) | (1 << 8) | (0 << 12);
		public static const YZYY : uint = 1 | (2 << 4) | (1 << 8) | (1 << 12);
		public static const YZYZ : uint = 1 | (2 << 4) | (1 << 8) | (2 << 12);
		public static const YZYW : uint = 1 | (2 << 4) | (1 << 8) | (3 << 12);
		public static const YZZX : uint = 1 | (2 << 4) | (2 << 8) | (0 << 12);
		public static const YZZY : uint = 1 | (2 << 4) | (2 << 8) | (1 << 12);
		public static const YZZZ : uint = 1 | (2 << 4) | (2 << 8) | (2 << 12);
		public static const YZZW : uint = 1 | (2 << 4) | (2 << 8) | (3 << 12);
		public static const YZWX : uint = 1 | (2 << 4) | (3 << 8) | (0 << 12);
		public static const YZWY : uint = 1 | (2 << 4) | (3 << 8) | (1 << 12);
		public static const YZWZ : uint = 1 | (2 << 4) | (3 << 8) | (2 << 12);
		public static const YZWW : uint = 1 | (2 << 4) | (3 << 8) | (3 << 12);
		public static const YWXX : uint = 1 | (3 << 4) | (0 << 8) | (0 << 12);
		public static const YWXY : uint = 1 | (3 << 4) | (0 << 8) | (1 << 12);
		public static const YWXZ : uint = 1 | (3 << 4) | (0 << 8) | (2 << 12);
		public static const YWXW : uint = 1 | (3 << 4) | (0 << 8) | (3 << 12);
		public static const YWYX : uint = 1 | (3 << 4) | (1 << 8) | (0 << 12);
		public static const YWYY : uint = 1 | (3 << 4) | (1 << 8) | (1 << 12);
		public static const YWYZ : uint = 1 | (3 << 4) | (1 << 8) | (2 << 12);
		public static const YWYW : uint = 1 | (3 << 4) | (1 << 8) | (3 << 12);
		public static const YWZX : uint = 1 | (3 << 4) | (2 << 8) | (0 << 12);
		public static const YWZY : uint = 1 | (3 << 4) | (2 << 8) | (1 << 12);
		public static const YWZZ : uint = 1 | (3 << 4) | (2 << 8) | (2 << 12);
		public static const YWZW : uint = 1 | (3 << 4) | (2 << 8) | (3 << 12);
		public static const YWWX : uint = 1 | (3 << 4) | (3 << 8) | (0 << 12);
		public static const YWWY : uint = 1 | (3 << 4) | (3 << 8) | (1 << 12);
		public static const YWWZ : uint = 1 | (3 << 4) | (3 << 8) | (2 << 12);
		public static const YWWW : uint = 1 | (3 << 4) | (3 << 8) | (3 << 12);
		public static const ZXXX : uint = 2 | (0 << 4) | (0 << 8) | (0 << 12);
		public static const ZXXY : uint = 2 | (0 << 4) | (0 << 8) | (1 << 12);
		public static const ZXXZ : uint = 2 | (0 << 4) | (0 << 8) | (2 << 12);
		public static const ZXXW : uint = 2 | (0 << 4) | (0 << 8) | (3 << 12);
		public static const ZXYX : uint = 2 | (0 << 4) | (1 << 8) | (0 << 12);
		public static const ZXYY : uint = 2 | (0 << 4) | (1 << 8) | (1 << 12);
		public static const ZXYZ : uint = 2 | (0 << 4) | (1 << 8) | (2 << 12);
		public static const ZXYW : uint = 2 | (0 << 4) | (1 << 8) | (3 << 12);
		public static const ZXZX : uint = 2 | (0 << 4) | (2 << 8) | (0 << 12);
		public static const ZXZY : uint = 2 | (0 << 4) | (2 << 8) | (1 << 12);
		public static const ZXZZ : uint = 2 | (0 << 4) | (2 << 8) | (2 << 12);
		public static const ZXZW : uint = 2 | (0 << 4) | (2 << 8) | (3 << 12);
		public static const ZXWX : uint = 2 | (0 << 4) | (3 << 8) | (0 << 12);
		public static const ZXWY : uint = 2 | (0 << 4) | (3 << 8) | (1 << 12);
		public static const ZXWZ : uint = 2 | (0 << 4) | (3 << 8) | (2 << 12);
		public static const ZXWW : uint = 2 | (0 << 4) | (3 << 8) | (3 << 12);
		public static const ZYXX : uint = 2 | (1 << 4) | (0 << 8) | (0 << 12);
		public static const ZYXY : uint = 2 | (1 << 4) | (0 << 8) | (1 << 12);
		public static const ZYXZ : uint = 2 | (1 << 4) | (0 << 8) | (2 << 12);
		public static const ZYXW : uint = 2 | (1 << 4) | (0 << 8) | (3 << 12);
		public static const ZYYX : uint = 2 | (1 << 4) | (1 << 8) | (0 << 12);
		public static const ZYYY : uint = 2 | (1 << 4) | (1 << 8) | (1 << 12);
		public static const ZYYZ : uint = 2 | (1 << 4) | (1 << 8) | (2 << 12);
		public static const ZYYW : uint = 2 | (1 << 4) | (1 << 8) | (3 << 12);
		public static const ZYZX : uint = 2 | (1 << 4) | (2 << 8) | (0 << 12);
		public static const ZYZY : uint = 2 | (1 << 4) | (2 << 8) | (1 << 12);
		public static const ZYZZ : uint = 2 | (1 << 4) | (2 << 8) | (2 << 12);
		public static const ZYZW : uint = 2 | (1 << 4) | (2 << 8) | (3 << 12);
		public static const ZYWX : uint = 2 | (1 << 4) | (3 << 8) | (0 << 12);
		public static const ZYWY : uint = 2 | (1 << 4) | (3 << 8) | (1 << 12);
		public static const ZYWZ : uint = 2 | (1 << 4) | (3 << 8) | (2 << 12);
		public static const ZYWW : uint = 2 | (1 << 4) | (3 << 8) | (3 << 12);
		public static const ZZXX : uint = 2 | (2 << 4) | (0 << 8) | (0 << 12);
		public static const ZZXY : uint = 2 | (2 << 4) | (0 << 8) | (1 << 12);
		public static const ZZXZ : uint = 2 | (2 << 4) | (0 << 8) | (2 << 12);
		public static const ZZXW : uint = 2 | (2 << 4) | (0 << 8) | (3 << 12);
		public static const ZZYX : uint = 2 | (2 << 4) | (1 << 8) | (0 << 12);
		public static const ZZYY : uint = 2 | (2 << 4) | (1 << 8) | (1 << 12);
		public static const ZZYZ : uint = 2 | (2 << 4) | (1 << 8) | (2 << 12);
		public static const ZZYW : uint = 2 | (2 << 4) | (1 << 8) | (3 << 12);
		public static const ZZZX : uint = 2 | (2 << 4) | (2 << 8) | (0 << 12);
		public static const ZZZY : uint = 2 | (2 << 4) | (2 << 8) | (1 << 12);
		public static const ZZZZ : uint = 2 | (2 << 4) | (2 << 8) | (2 << 12);
		public static const ZZZW : uint = 2 | (2 << 4) | (2 << 8) | (3 << 12);
		public static const ZZWX : uint = 2 | (2 << 4) | (3 << 8) | (0 << 12);
		public static const ZZWY : uint = 2 | (2 << 4) | (3 << 8) | (1 << 12);
		public static const ZZWZ : uint = 2 | (2 << 4) | (3 << 8) | (2 << 12);
		public static const ZZWW : uint = 2 | (2 << 4) | (3 << 8) | (3 << 12);
		public static const ZWXX : uint = 2 | (3 << 4) | (0 << 8) | (0 << 12);
		public static const ZWXY : uint = 2 | (3 << 4) | (0 << 8) | (1 << 12);
		public static const ZWXZ : uint = 2 | (3 << 4) | (0 << 8) | (2 << 12);
		public static const ZWXW : uint = 2 | (3 << 4) | (0 << 8) | (3 << 12);
		public static const ZWYX : uint = 2 | (3 << 4) | (1 << 8) | (0 << 12);
		public static const ZWYY : uint = 2 | (3 << 4) | (1 << 8) | (1 << 12);
		public static const ZWYZ : uint = 2 | (3 << 4) | (1 << 8) | (2 << 12);
		public static const ZWYW : uint = 2 | (3 << 4) | (1 << 8) | (3 << 12);
		public static const ZWZX : uint = 2 | (3 << 4) | (2 << 8) | (0 << 12);
		public static const ZWZY : uint = 2 | (3 << 4) | (2 << 8) | (1 << 12);
		public static const ZWZZ : uint = 2 | (3 << 4) | (2 << 8) | (2 << 12);
		public static const ZWZW : uint = 2 | (3 << 4) | (2 << 8) | (3 << 12);
		public static const ZWWX : uint = 2 | (3 << 4) | (3 << 8) | (0 << 12);
		public static const ZWWY : uint = 2 | (3 << 4) | (3 << 8) | (1 << 12);
		public static const ZWWZ : uint = 2 | (3 << 4) | (3 << 8) | (2 << 12);
		public static const ZWWW : uint = 2 | (3 << 4) | (3 << 8) | (3 << 12);
		public static const WXXX : uint = 3 | (0 << 4) | (0 << 8) | (0 << 12);
		public static const WXXY : uint = 3 | (0 << 4) | (0 << 8) | (1 << 12);
		public static const WXXZ : uint = 3 | (0 << 4) | (0 << 8) | (2 << 12);
		public static const WXXW : uint = 3 | (0 << 4) | (0 << 8) | (3 << 12);
		public static const WXYX : uint = 3 | (0 << 4) | (1 << 8) | (0 << 12);
		public static const WXYY : uint = 3 | (0 << 4) | (1 << 8) | (1 << 12);
		public static const WXYZ : uint = 3 | (0 << 4) | (1 << 8) | (2 << 12);
		public static const WXYW : uint = 3 | (0 << 4) | (1 << 8) | (3 << 12);
		public static const WXZX : uint = 3 | (0 << 4) | (2 << 8) | (0 << 12);
		public static const WXZY : uint = 3 | (0 << 4) | (2 << 8) | (1 << 12);
		public static const WXZZ : uint = 3 | (0 << 4) | (2 << 8) | (2 << 12);
		public static const WXZW : uint = 3 | (0 << 4) | (2 << 8) | (3 << 12);
		public static const WXWX : uint = 3 | (0 << 4) | (3 << 8) | (0 << 12);
		public static const WXWY : uint = 3 | (0 << 4) | (3 << 8) | (1 << 12);
		public static const WXWZ : uint = 3 | (0 << 4) | (3 << 8) | (2 << 12);
		public static const WXWW : uint = 3 | (0 << 4) | (3 << 8) | (3 << 12);
		public static const WYXX : uint = 3 | (1 << 4) | (0 << 8) | (0 << 12);
		public static const WYXY : uint = 3 | (1 << 4) | (0 << 8) | (1 << 12);
		public static const WYXZ : uint = 3 | (1 << 4) | (0 << 8) | (2 << 12);
		public static const WYXW : uint = 3 | (1 << 4) | (0 << 8) | (3 << 12);
		public static const WYYX : uint = 3 | (1 << 4) | (1 << 8) | (0 << 12);
		public static const WYYY : uint = 3 | (1 << 4) | (1 << 8) | (1 << 12);
		public static const WYYZ : uint = 3 | (1 << 4) | (1 << 8) | (2 << 12);
		public static const WYYW : uint = 3 | (1 << 4) | (1 << 8) | (3 << 12);
		public static const WYZX : uint = 3 | (1 << 4) | (2 << 8) | (0 << 12);
		public static const WYZY : uint = 3 | (1 << 4) | (2 << 8) | (1 << 12);
		public static const WYZZ : uint = 3 | (1 << 4) | (2 << 8) | (2 << 12);
		public static const WYZW : uint = 3 | (1 << 4) | (2 << 8) | (3 << 12);
		public static const WYWX : uint = 3 | (1 << 4) | (3 << 8) | (0 << 12);
		public static const WYWY : uint = 3 | (1 << 4) | (3 << 8) | (1 << 12);
		public static const WYWZ : uint = 3 | (1 << 4) | (3 << 8) | (2 << 12);
		public static const WYWW : uint = 3 | (1 << 4) | (3 << 8) | (3 << 12);
		public static const WZXX : uint = 3 | (2 << 4) | (0 << 8) | (0 << 12);
		public static const WZXY : uint = 3 | (2 << 4) | (0 << 8) | (1 << 12);
		public static const WZXZ : uint = 3 | (2 << 4) | (0 << 8) | (2 << 12);
		public static const WZXW : uint = 3 | (2 << 4) | (0 << 8) | (3 << 12);
		public static const WZYX : uint = 3 | (2 << 4) | (1 << 8) | (0 << 12);
		public static const WZYY : uint = 3 | (2 << 4) | (1 << 8) | (1 << 12);
		public static const WZYZ : uint = 3 | (2 << 4) | (1 << 8) | (2 << 12);
		public static const WZYW : uint = 3 | (2 << 4) | (1 << 8) | (3 << 12);
		public static const WZZX : uint = 3 | (2 << 4) | (2 << 8) | (0 << 12);
		public static const WZZY : uint = 3 | (2 << 4) | (2 << 8) | (1 << 12);
		public static const WZZZ : uint = 3 | (2 << 4) | (2 << 8) | (2 << 12);
		public static const WZZW : uint = 3 | (2 << 4) | (2 << 8) | (3 << 12);
		public static const WZWX : uint = 3 | (2 << 4) | (3 << 8) | (0 << 12);
		public static const WZWY : uint = 3 | (2 << 4) | (3 << 8) | (1 << 12);
		public static const WZWZ : uint = 3 | (2 << 4) | (3 << 8) | (2 << 12);
		public static const WZWW : uint = 3 | (2 << 4) | (3 << 8) | (3 << 12);
		public static const WWXX : uint = 3 | (3 << 4) | (0 << 8) | (0 << 12);
		public static const WWXY : uint = 3 | (3 << 4) | (0 << 8) | (1 << 12);
		public static const WWXZ : uint = 3 | (3 << 4) | (0 << 8) | (2 << 12);
		public static const WWXW : uint = 3 | (3 << 4) | (0 << 8) | (3 << 12);
		public static const WWYX : uint = 3 | (3 << 4) | (1 << 8) | (0 << 12);
		public static const WWYY : uint = 3 | (3 << 4) | (1 << 8) | (1 << 12);
		public static const WWYZ : uint = 3 | (3 << 4) | (1 << 8) | (2 << 12);
		public static const WWYW : uint = 3 | (3 << 4) | (1 << 8) | (3 << 12);
		public static const WWZX : uint = 3 | (3 << 4) | (2 << 8) | (0 << 12);
		public static const WWZY : uint = 3 | (3 << 4) | (2 << 8) | (1 << 12);
		public static const WWZZ : uint = 3 | (3 << 4) | (2 << 8) | (2 << 12);
		public static const WWZW : uint = 3 | (3 << 4) | (2 << 8) | (3 << 12);
		public static const WWWX : uint = 3 | (3 << 4) | (3 << 8) | (0 << 12);
		public static const WWWY : uint = 3 | (3 << 4) | (3 << 8) | (1 << 12);
		public static const WWWZ : uint = 3 | (3 << 4) | (3 << 8) | (2 << 12);
		public static const WWWW : uint = 3 | (3 << 4) | (3 << 8) | (3 << 12);

		public static const R : uint = X
		public static const G : uint = Y
		public static const B : uint = Z
		public static const A : uint = W
		public static const RR : uint = XX
		public static const RG : uint = XY
		public static const RB : uint = XZ
		public static const RA : uint = XW
		public static const GR : uint = YX
		public static const GG : uint = YY
		public static const GB : uint = YZ
		public static const GA : uint = YW
		public static const BR : uint = ZX
		public static const BG : uint = ZY
		public static const BB : uint = ZZ
		public static const BA : uint = ZW
		public static const AR : uint = WX
		public static const AG : uint = WY
		public static const AB : uint = WZ
		public static const AA : uint = WW
		public static const RRR : uint = XXX
		public static const RRG : uint = XXY
		public static const RRB : uint = XXZ
		public static const RRA : uint = XXW
		public static const RGR : uint = XYX
		public static const RGG : uint = XYY
		public static const RGB : uint = XYZ
		public static const RGA : uint = XYW
		public static const RBR : uint = XZX
		public static const RBG : uint = XZY
		public static const RBB : uint = XZZ
		public static const RBA : uint = XZW
		public static const RAR : uint = XWX
		public static const RAG : uint = XWY
		public static const RAB : uint = XWZ
		public static const RAA : uint = XWW
		public static const GRR : uint = YXX
		public static const GRG : uint = YXY
		public static const GRB : uint = YXZ
		public static const GRA : uint = YXW
		public static const GGR : uint = YYX
		public static const GGG : uint = YYY
		public static const GGB : uint = YYZ
		public static const GGA : uint = YYW
		public static const GBR : uint = YZX
		public static const GBG : uint = YZY
		public static const GBB : uint = YZZ
		public static const GBA : uint = YZW
		public static const GAR : uint = YWX
		public static const GAG : uint = YWY
		public static const GAB : uint = YWZ
		public static const GAA : uint = YWW
		public static const BRR : uint = ZXX
		public static const BRG : uint = ZXY
		public static const BRB : uint = ZXZ
		public static const BRA : uint = ZXW
		public static const BGR : uint = ZYX
		public static const BGG : uint = ZYY
		public static const BGB : uint = ZYZ
		public static const BGA : uint = ZYW
		public static const BBR : uint = ZZX
		public static const BBG : uint = ZZY
		public static const BBB : uint = ZZZ
		public static const BBA : uint = ZZW
		public static const BAR : uint = ZWX
		public static const BAG : uint = ZWY
		public static const BAB : uint = ZWZ
		public static const BAA : uint = ZWW
		public static const ARR : uint = WXX
		public static const ARG : uint = WXY
		public static const ARB : uint = WXZ
		public static const ARA : uint = WXW
		public static const AGR : uint = WYX
		public static const AGG : uint = WYY
		public static const AGB : uint = WYZ
		public static const AGA : uint = WYW
		public static const ABR : uint = WZX
		public static const ABG : uint = WZY
		public static const ABB : uint = WZZ
		public static const ABA : uint = WZW
		public static const AAR : uint = WWX
		public static const AAG : uint = WWY
		public static const AAB : uint = WWZ
		public static const AAA : uint = WWW
		public static const RRRR : uint = XXXX
		public static const RRRG : uint = XXXY
		public static const RRRB : uint = XXXZ
		public static const RRRA : uint = XXXW
		public static const RRGR : uint = XXYX
		public static const RRGG : uint = XXYY
		public static const RRGB : uint = XXYZ
		public static const RRGA : uint = XXYW
		public static const RRBR : uint = XXZX
		public static const RRBG : uint = XXZY
		public static const RRBB : uint = XXZZ
		public static const RRBA : uint = XXZW
		public static const RRAR : uint = XXWX
		public static const RRAG : uint = XXWY
		public static const RRAB : uint = XXWZ
		public static const RRAA : uint = XXWW
		public static const RGRR : uint = XYXX
		public static const RGRG : uint = XYXY
		public static const RGRB : uint = XYXZ
		public static const RGRA : uint = XYXW
		public static const RGGR : uint = XYYX
		public static const RGGG : uint = XYYY
		public static const RGGB : uint = XYYZ
		public static const RGGA : uint = XYYW
		public static const RGBR : uint = XYZX
		public static const RGBG : uint = XYZY
		public static const RGBB : uint = XYZZ
		public static const RGBA : uint = XYZW
		public static const RGAR : uint = XYWX
		public static const RGAG : uint = XYWY
		public static const RGAB : uint = XYWZ
		public static const RGAA : uint = XYWW
		public static const RBRR : uint = XZXX
		public static const RBRG : uint = XZXY
		public static const RBRB : uint = XZXZ
		public static const RBRA : uint = XZXW
		public static const RBGR : uint = XZYX
		public static const RBGG : uint = XZYY
		public static const RBGB : uint = XZYZ
		public static const RBGA : uint = XZYW
		public static const RBBR : uint = XZZX
		public static const RBBG : uint = XZZY
		public static const RBBB : uint = XZZZ
		public static const RBBA : uint = XZZW
		public static const RBAR : uint = XZWX
		public static const RBAG : uint = XZWY
		public static const RBAB : uint = XZWZ
		public static const RBAA : uint = XZWW
		public static const RARR : uint = XWXX
		public static const RARG : uint = XWXY
		public static const RARB : uint = XWXZ
		public static const RARA : uint = XWXW
		public static const RAGR : uint = XWYX
		public static const RAGG : uint = XWYY
		public static const RAGB : uint = XWYZ
		public static const RAGA : uint = XWYW
		public static const RABR : uint = XWZX
		public static const RABG : uint = XWZY
		public static const RABB : uint = XWZZ
		public static const RABA : uint = XWZW
		public static const RAAR : uint = XWWX
		public static const RAAG : uint = XWWY
		public static const RAAB : uint = XWWZ
		public static const RAAA : uint = XWWW
		public static const GRRR : uint = YXXX
		public static const GRRG : uint = YXXY
		public static const GRRB : uint = YXXZ
		public static const GRRA : uint = YXXW
		public static const GRGR : uint = YXYX
		public static const GRGG : uint = YXYY
		public static const GRGB : uint = YXYZ
		public static const GRGA : uint = YXYW
		public static const GRBR : uint = YXZX
		public static const GRBG : uint = YXZY
		public static const GRBB : uint = YXZZ
		public static const GRBA : uint = YXZW
		public static const GRAR : uint = YXWX
		public static const GRAG : uint = YXWY
		public static const GRAB : uint = YXWZ
		public static const GRAA : uint = YXWW
		public static const GGRR : uint = YYXX
		public static const GGRG : uint = YYXY
		public static const GGRB : uint = YYXZ
		public static const GGRA : uint = YYXW
		public static const GGGR : uint = YYYX
		public static const GGGG : uint = YYYY
		public static const GGGB : uint = YYYZ
		public static const GGGA : uint = YYYW
		public static const GGBR : uint = YYZX
		public static const GGBG : uint = YYZY
		public static const GGBB : uint = YYZZ
		public static const GGBA : uint = YYZW
		public static const GGAR : uint = YYWX
		public static const GGAG : uint = YYWY
		public static const GGAB : uint = YYWZ
		public static const GGAA : uint = YYWW
		public static const GBRR : uint = YZXX
		public static const GBRG : uint = YZXY
		public static const GBRB : uint = YZXZ
		public static const GBRA : uint = YZXW
		public static const GBGR : uint = YZYX
		public static const GBGG : uint = YZYY
		public static const GBGB : uint = YZYZ
		public static const GBGA : uint = YZYW
		public static const GBBR : uint = YZZX
		public static const GBBG : uint = YZZY
		public static const GBBB : uint = YZZZ
		public static const GBBA : uint = YZZW
		public static const GBAR : uint = YZWX
		public static const GBAG : uint = YZWY
		public static const GBAB : uint = YZWZ
		public static const GBAA : uint = YZWW
		public static const GARR : uint = YWXX
		public static const GARG : uint = YWXY
		public static const GARB : uint = YWXZ
		public static const GARA : uint = YWXW
		public static const GAGR : uint = YWYX
		public static const GAGG : uint = YWYY
		public static const GAGB : uint = YWYZ
		public static const GAGA : uint = YWYW
		public static const GABR : uint = YWZX
		public static const GABG : uint = YWZY
		public static const GABB : uint = YWZZ
		public static const GABA : uint = YWZW
		public static const GAAR : uint = YWWX
		public static const GAAG : uint = YWWY
		public static const GAAB : uint = YWWZ
		public static const GAAA : uint = YWWW
		public static const BRRR : uint = ZXXX
		public static const BRRG : uint = ZXXY
		public static const BRRB : uint = ZXXZ
		public static const BRRA : uint = ZXXW
		public static const BRGR : uint = ZXYX
		public static const BRGG : uint = ZXYY
		public static const BRGB : uint = ZXYZ
		public static const BRGA : uint = ZXYW
		public static const BRBR : uint = ZXZX
		public static const BRBG : uint = ZXZY
		public static const BRBB : uint = ZXZZ
		public static const BRBA : uint = ZXZW
		public static const BRAR : uint = ZXWX
		public static const BRAG : uint = ZXWY
		public static const BRAB : uint = ZXWZ
		public static const BRAA : uint = ZXWW
		public static const BGRR : uint = ZYXX
		public static const BGRG : uint = ZYXY
		public static const BGRB : uint = ZYXZ
		public static const BGRA : uint = ZYXW
		public static const BGGR : uint = ZYYX
		public static const BGGG : uint = ZYYY
		public static const BGGB : uint = ZYYZ
		public static const BGGA : uint = ZYYW
		public static const BGBR : uint = ZYZX
		public static const BGBG : uint = ZYZY
		public static const BGBB : uint = ZYZZ
		public static const BGBA : uint = ZYZW
		public static const BGAR : uint = ZYWX
		public static const BGAG : uint = ZYWY
		public static const BGAB : uint = ZYWZ
		public static const BGAA : uint = ZYWW
		public static const BBRR : uint = ZZXX
		public static const BBRG : uint = ZZXY
		public static const BBRB : uint = ZZXZ
		public static const BBRA : uint = ZZXW
		public static const BBGR : uint = ZZYX
		public static const BBGG : uint = ZZYY
		public static const BBGB : uint = ZZYZ
		public static const BBGA : uint = ZZYW
		public static const BBBR : uint = ZZZX
		public static const BBBG : uint = ZZZY
		public static const BBBB : uint = ZZZZ
		public static const BBBA : uint = ZZZW
		public static const BBAR : uint = ZZWX
		public static const BBAG : uint = ZZWY
		public static const BBAB : uint = ZZWZ
		public static const BBAA : uint = ZZWW
		public static const BARR : uint = ZWXX
		public static const BARG : uint = ZWXY
		public static const BARB : uint = ZWXZ
		public static const BARA : uint = ZWXW
		public static const BAGR : uint = ZWYX
		public static const BAGG : uint = ZWYY
		public static const BAGB : uint = ZWYZ
		public static const BAGA : uint = ZWYW
		public static const BABR : uint = ZWZX
		public static const BABG : uint = ZWZY
		public static const BABB : uint = ZWZZ
		public static const BABA : uint = ZWZW
		public static const BAAR : uint = ZWWX
		public static const BAAG : uint = ZWWY
		public static const BAAB : uint = ZWWZ
		public static const BAAA : uint = ZWWW
		public static const ARRR : uint = WXXX
		public static const ARRG : uint = WXXY
		public static const ARRB : uint = WXXZ
		public static const ARRA : uint = WXXW
		public static const ARGR : uint = WXYX
		public static const ARGG : uint = WXYY
		public static const ARGB : uint = WXYZ
		public static const ARGA : uint = WXYW
		public static const ARBR : uint = WXZX
		public static const ARBG : uint = WXZY
		public static const ARBB : uint = WXZZ
		public static const ARBA : uint = WXZW
		public static const ARAR : uint = WXWX
		public static const ARAG : uint = WXWY
		public static const ARAB : uint = WXWZ
		public static const ARAA : uint = WXWW
		public static const AGRR : uint = WYXX
		public static const AGRG : uint = WYXY
		public static const AGRB : uint = WYXZ
		public static const AGRA : uint = WYXW
		public static const AGGR : uint = WYYX
		public static const AGGG : uint = WYYY
		public static const AGGB : uint = WYYZ
		public static const AGGA : uint = WYYW
		public static const AGBR : uint = WYZX
		public static const AGBG : uint = WYZY
		public static const AGBB : uint = WYZZ
		public static const AGBA : uint = WYZW
		public static const AGAR : uint = WYWX
		public static const AGAG : uint = WYWY
		public static const AGAB : uint = WYWZ
		public static const AGAA : uint = WYWW
		public static const ABRR : uint = WZXX
		public static const ABRG : uint = WZXY
		public static const ABRB : uint = WZXZ
		public static const ABRA : uint = WZXW
		public static const ABGR : uint = WZYX
		public static const ABGG : uint = WZYY
		public static const ABGB : uint = WZYZ
		public static const ABGA : uint = WZYW
		public static const ABBR : uint = WZZX
		public static const ABBG : uint = WZZY
		public static const ABBB : uint = WZZZ
		public static const ABBA : uint = WZZW
		public static const ABAR : uint = WZWX
		public static const ABAG : uint = WZWY
		public static const ABAB : uint = WZWZ
		public static const ABAA : uint = WZWW
		public static const AARR : uint = WWXX
		public static const AARG : uint = WWXY
		public static const AARB : uint = WWXZ
		public static const AARA : uint = WWXW
		public static const AAGR : uint = WWYX
		public static const AAGG : uint = WWYY
		public static const AAGB : uint = WWYZ
		public static const AAGA : uint = WWYW
		public static const AABR : uint = WWZX
		public static const AABG : uint = WWZY
		public static const AABB : uint = WWZZ
		public static const AABA : uint = WWZW
		public static const AAAR : uint = WWWX
		public static const AAAG : uint = WWWY
		public static const AAAB : uint = WWWZ
		public static const AAAA : uint = WWWW

		public static function getSwizzle(part : uint) : uint
		{
			var part1	: uint = part			& 0xF;
			var part2	: uint = (part >>> 4)	& 0xF;
			var part3	: uint = (part >>> 8)	& 0xF;
			var part4	: uint = (part >>> 12)	& 0xF;

			if (part2 == 4) part2 = part1;
			if (part3 == 4) part3 = part2;
			if (part4 == 4) part4 = part3;

			return part1 | (part2 << 2) | (part3 << 4) | (part4 << 6);
		}

		public static function getSize(part : uint) : uint
		{
			var part1	: uint = part			& 0xF;
			var part2	: uint = (part >>> 4)	& 0xF;
			var part3	: uint = (part >>> 8)	& 0xF;
			var part4	: uint = (part >>> 12)	& 0xF;

			if (part1 == 4)
				return 0;
			else if (part2 == 4)
				return 1;
			else if (part3 == 4)
				return 2;
			else if (part4 == 4)
				return 3;
			else
				return 4;
		}

	}
}
