LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := bullet-collision
LOCAL_CFLAGS :=
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../

LOCAL_SRC_FILES := BroadphaseCollision/btAxisSweep3.cpp \
BroadphaseCollision/btBroadphaseProxy.cpp \
BroadphaseCollision/btCollisionAlgorithm.cpp \
BroadphaseCollision/btDbvt.cpp \
BroadphaseCollision/btDbvtBroadphase.cpp \
BroadphaseCollision/btDispatcher.cpp \
BroadphaseCollision/btMultiSapBroadphase.cpp \
BroadphaseCollision/btOverlappingPairCache.cpp \
BroadphaseCollision/btQuantizedBvh.cpp \
BroadphaseCollision/btSimpleBroadphase.cpp \
CollisionDispatch/SphereTriangleDetector.cpp \
CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
CollisionDispatch/btBoxBoxDetector.cpp \
CollisionDispatch/btCollisionDispatcher.cpp \
CollisionDispatch/btCollisionObject.cpp \
CollisionDispatch/btCollisionWorld.cpp \
CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
CollisionDispatch/btConvexConvexAlgorithm.cpp \
CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
CollisionDispatch/btDefaultCollisionConfiguration.cpp \
CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
CollisionDispatch/btGhostObject.cpp \
CollisionDispatch/btInternalEdgeUtility.cpp \
CollisionDispatch/btManifoldResult.cpp \
CollisionDispatch/btSimulationIslandManager.cpp \
CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
CollisionDispatch/btUnionFind.cpp \
CollisionShapes/btUniformScalingShape.h \
CollisionShapes/btBox2dShape.cpp \
CollisionShapes/btBoxShape.cpp \
CollisionShapes/btBvhTriangleMeshShape.cpp \
CollisionShapes/btCapsuleShape.cpp \
CollisionShapes/btCollisionShape.cpp \
CollisionShapes/btCompoundShape.cpp \
CollisionShapes/btConcaveShape.cpp \
CollisionShapes/btConeShape.cpp \
CollisionShapes/btConvex2dShape.cpp \
CollisionShapes/btConvexHullShape.cpp \
CollisionShapes/btConvexInternalShape.cpp \
CollisionShapes/btConvexPointCloudShape.cpp \
CollisionShapes/btConvexPolyhedron.cpp \
CollisionShapes/btConvexShape.cpp \
CollisionShapes/btConvexTriangleMeshShape.cpp \
CollisionShapes/btCylinderShape.cpp \
CollisionShapes/btEmptyShape.cpp \
CollisionShapes/btHeightfieldTerrainShape.cpp \
CollisionShapes/btMinkowskiSumShape.cpp \
CollisionShapes/btMultiSphereShape.cpp \
CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
CollisionShapes/btOptimizedBvh.cpp \
CollisionShapes/btPolyhedralConvexShape.cpp \
CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
CollisionShapes/btShapeHull.cpp \
CollisionShapes/btSphereShape.cpp \
CollisionShapes/btStaticPlaneShape.cpp \
CollisionShapes/btStridingMeshInterface.cpp \
CollisionShapes/btTetrahedronShape.cpp \
CollisionShapes/btTriangleBuffer.cpp \
CollisionShapes/btTriangleCallback.cpp \
CollisionShapes/btTriangleIndexVertexArray.cpp \
CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
CollisionShapes/btTriangleMesh.cpp \
CollisionShapes/btTriangleMeshShape.cpp \
CollisionShapes/btUniformScalingShape.cpp \
Gimpact/btContactProcessing.cpp \
Gimpact/btGImpactBvh.cpp \
Gimpact/btGImpactCollisionAlgorithm.cpp \
Gimpact/btGImpactQuantizedBvh.cpp \
Gimpact/btGImpactShape.cpp \
Gimpact/btGenericPoolAllocator.cpp \
Gimpact/btTriangleShapeEx.cpp \
Gimpact/gim_box_set.cpp \
Gimpact/gim_contact.cpp \
Gimpact/gim_memory.cpp \
Gimpact/gim_tri_collision.cpp \
NarrowPhaseCollision/btContinuousConvexCollision.cpp \
NarrowPhaseCollision/btConvexCast.cpp \
NarrowPhaseCollision/btGjkConvexCast.cpp \
NarrowPhaseCollision/btGjkEpa2.cpp \
NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
NarrowPhaseCollision/btGjkPairDetector.cpp \
NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
NarrowPhaseCollision/btPersistentManifold.cpp \
NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
NarrowPhaseCollision/btRaycastCallback.cpp \
NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
NarrowPhaseCollision/btVoronoiSimplexSolver.cpp

include $(BUILD_STATIC_LIBRARY)
