#!/bin/sh

declare -A loaders

# (parser name <-> assimp file name) mapping
loaders["Discreet3DS"]="3DSLoader"
loaders["AC3D"]="ACLoader"
loaders["ASE"]="ASELoader"
loaders["B3D"]="B3DImporter"
loaders["Blender"]="BlenderLoader"
loaders["BVH"]="BVHLoader"
loaders["COB"]="COBLoader"
loaders["Collada"]="ColladaLoader"
loaders["CSM"]="CSMLoader"
loaders["DXF"]="DXFLoader"
loaders["FBX"]="FBXImporter"
loaders["HMP"]="HMPLoader"
loaders["IFC"]="IFCLoader"
loaders["IRR"]="IRRLoader"
loaders["LWO"]="LWOLoader"
loaders["LWS"]="LWSLoader"
loaders["MD2"]="MD2Loader"
loaders["MD3"]="MD3Loader"
loaders["MD5"]="MD5Loader"
loaders["MDC"]="MDCLoader"
loaders["MDL"]="MDLLoader"
loaders["MS3D"]="MS3DLoader"
loaders["NDO"]="NDOLoader"
loaders["NFF"]="NFFLoader"
loaders["ObjFile"]="ObjFileImporter"
loaders["ObjFileMtl"]="ObjFileMtlImporter"
loaders["OFF"]="OFFLoader"
loaders["Ogre"]="OgreImporter"
loaders["Ply"]="PlyLoader"
loaders["Q3BSPFile"]="Q3BSPFileImporter"
loaders["Q3D"]="Q3DLoader"
loaders["Raw"]="RawLoader"
loaders["SMD"]="SMDLoader"
loaders["STL"]="STLLoader"
loaders["Terragen"]="TerragenLoader"
loaders["Unreal"]="UnrealLoader"
loaders["XFile"]="XFileImporter"
loaders["XGL"]="XGLLoader"
