#!/bin/bash

declare -A loaders

# (parser name <-> assimp file name) mapping

loaders["Discreet3DS"]="3DSLoader.h"
loaders["AC3D"]="ACLoader.h"
loaders["ASE"]="ASELoader.h"
loaders["B3D"]="B3DImporter.h"
loaders["Blender"]="BlenderLoader.h"
loaders["BVH"]="BVHLoader.h"
loaders["COB"]="COBLoader.h"
loaders["Collada"]="ColladaLoader.h"
loaders["CSM"]="CSMLoader.h"
loaders["DXF"]="DXFLoader.h"
loaders["FBX"]="FBXImporter.h"
loaders["HMP"]="HMPLoader.h"
loaders["IFC"]="IFCLoader.h"
loaders["IRR"]="IRRLoader.h"
loaders["LWO"]="LWOLoader.h"
loaders["LWS"]="LWSLoader.h"
loaders["MD2"]="MD2Loader.h"
loaders["MD3"]="MD3Loader.h"
loaders["MD5"]="MD5Loader.h"
loaders["MDC"]="MDCLoader.h"
loaders["MDL"]="MDLLoader.h"
loaders["MS3D"]="MS3DLoader.h"
loaders["NDO"]="NDOLoader.h"
loaders["NFF"]="NFFLoader.h"
loaders["ObjFile"]="ObjFileImporter.h"
loaders["OFF"]="OFFLoader.h"
# note: OgreImporter is nested in Assimp::Ogre namespace; TODO handle special case
# loaders["Ogre"]="OgreImporter.hpp"
loaders["PLY"]="PlyLoader.h"
loaders["Q3BSPFile"]="Q3BSPFileImporter.h"
loaders["Q3D"]="Q3DLoader.h"
loaders["RAW"]="RawLoader.h"
loaders["SMD"]="SMDLoader.h"
loaders["STL"]="STLLoader.h"
loaders["Terragen"]="TerragenLoader.h"
loaders["Unreal"]="UnrealLoader.h"
loaders["XFile"]="XFileImporter.h"
loaders["XGL"]="XGLLoader.h"
