function (minko_enable_plugin_leap target)
    if (ANDROID OR IOS OR EMSCRIPTEN)
        return ()
    endif ()
    set (LEAP_PATH "${MINKO_HOME}/plugin/leap")
    minko_plugin_link ("leap" ${target})
    target_include_directories(${target} PRIVATE "${LEAP_PATH}/include")
    target_compile_options(${target} PRIVATE "-DMINKO_PLUGIN_LEAP")
    if (WIN32)
        target_link_libraries(${target} "${LEAP_PATH}/lib/leap/lib/windows${BITNESS}/Leap.lib")
        file (COPY "${LEAP_PATH}/lib/leap/lib/windows${BITNESS}/Leap.dll" DESTINATION "${OUTPUT_PATH}")
        file (COPY "${LEAP_PATH}/lib/leap/lib/windows${BITNESS}/Leapd.dll" DESTINATION "${OUTPUT_PATH}")
    endif ()
    if (UNIX AND NOT APPLE)
        target_link_libraries(${target} "${LEAP_PATH}/lib/leap/lib/linux${BITNESS}/libLeap.so")
        file (COPY "${LEAP_PATH}/lib/leap/lib/linux${BITNESS}/libLeap.so" DESTINATION "${OUTPUT_PATH}")
    endif ()
    if (APPLE)
        target_link_libraries(${target} "${LEAP_PATH}/lib/leap/lib/osx64/libLeap.dylib")
        file (COPY "${LEAP_PATH}/lib/leap/lib/osx64/libLeap.dylib" DESTINATION "${OUTPUT_PATH}")
    endif ()
endfunction ()